package it.alessioricco.btc.fragments;

import android.content.Context;
import android.graphics.Color;
import android.net.Uri;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;

import java.util.ArrayList;
import java.util.List;

import butterknife.ButterKnife;
import it.alessioricco.btc.R;
import it.alessioricco.btc.models.HistoricalValue;
import it.alessioricco.btc.models.MarketHistory;
import lecho.lib.hellocharts.model.Axis;
import lecho.lib.hellocharts.model.AxisValue;
import lecho.lib.hellocharts.model.Line;
import lecho.lib.hellocharts.model.LineChartData;
import lecho.lib.hellocharts.model.PointValue;
import lecho.lib.hellocharts.model.Viewport;

/**
 * A simple {@link Fragment} subclass.
 * Activities that contain this fragment must implement the
 */
public class Chart extends Fragment {

    public static final String ARG_HISTORY = "history";

    lecho.lib.hellocharts.view.LineChartView chart;


    public Chart() {
        // Required empty public constructor
    }


    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        if (getArguments() != null) {
            MarketHistory mHistory = (MarketHistory) getArguments().getSerializable(ARG_HISTORY);
            drawChart(mHistory);
        }
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        return inflater.inflate(R.layout.fragment_chart, container, false);
    }

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
    }

    @Override
    public void onDetach() {
        super.onDetach();
    }

    final public void showError(int visibility) {
        TextView text = ButterKnife.findById(this.getActivity(), R.id.notAvailable);
        if (text == null) {
            return;
        }
        text.setVisibility(visibility);

        LinearLayout chartLayout = ButterKnife.findById(this.getActivity(), R.id.chart_layout_container);
        if (chartLayout == null) {
            return;
        }
        chartLayout.setVisibility((visibility != View.VISIBLE) ? View.VISIBLE : View.INVISIBLE);
    }

    final public void update(MarketHistory marketHistory) {
        drawChart(marketHistory);
    }

    private void drawChart(MarketHistory marketHistory) {

        chart = ButterKnife.findById(this.getActivity(), R.id.chart);

        if (chart == null) {
            return;
        }

        if (marketHistory == null) {
            return;
        }

        final List<PointValue> values = new ArrayList<>();
        final List<AxisValue> axisXValues = new ArrayList<>();

        for(int i = 0; i< MarketHistory.getMaxSamples(); i++ ){

            final HistoricalValue historicalValue = marketHistory.get(i);
            if (historicalValue == null) {
                continue;
            }

            final Double d = historicalValue.getValue();
            if (d == null) {
                continue;
            }

            final float value = historicalValue.getValue().floatValue();
            values.add(new PointValue(i, value));

            final AxisValue axisValue = new AxisValue(i);
            final HistorySamplingDescriptor sampleDescriptor = HistorySamplingHelper.getSampleDescriptor(i);
            if (sampleDescriptor != null) {
                axisValue.setLabel(sampleDescriptor.getLabel());
                axisXValues.add(axisValue);
            }

        }

        final Line line = new Line(values)
                .setColor(Color.YELLOW)
                .setHasPoints(true)
                .setCubic(true);

        final List<Line> lines = new ArrayList<>();
        lines.add(line);
        final LineChartData lineChartData = new LineChartData();
        lineChartData.setLines(lines);

        final Axis axisY = new Axis().setHasLines(true).setAutoGenerated(true);
        final Axis axisX = new Axis().setHasLines(false).setValues(axisXValues);

        lineChartData.setAxisXBottom(axisX);
        lineChartData.setAxisYLeft(axisY);

        chart.setLineChartData(lineChartData);

        //https://github.com/lecho/hellocharts-android/issues/246
        final Viewport v = new Viewport(chart.getMaximumViewport());
        final int offset = 5;
        v.top = v.top + offset;
        v.bottom = v.bottom - offset;
        chart.setMaximumViewport(v);
        chart.setCurrentViewport(v);

    }
}
